In [1]:
%matplotlib inline
import numpy as np
import pandas as pd

np.random.seed(29)

### 1) How likely is it that you roll doubles when rolling two dice?

In [32]:
n_trials = nrows = 10**5
n_dice = ncols = 2

In [33]:
rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[5, 1],
       [3, 1],
       [1, 6],
       ...,
       [1, 5],
       [5, 3],
       [5, 2]])

In [35]:
#create a dataframe to get columns for rolls

rolls = (pd.DataFrame(rolls))

In [36]:
rolls.head()

0  1
0  5  1
1  3  1
2  1  6
3  4  1
4  4  4

In [37]:
rolls.columns

RangeIndex(start=0, stop=2, step=1)

In [38]:
#name the columns (roll vs roll2)
rolls.columns = ['rolls1','rolls2']

In [39]:
rolls.columns

Index(['rolls1', 'rolls2'], dtype='object')

In [45]:
#find the average of doubles rolled
(rolls.rolls1 == rolls.rolls2).mean()

0.16857

note: this makes sense as the probablity of two dice rolls being doubles as a 6:36 chance (6 sided dice X 6) and 0.16 = 1/6

### 2) If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [137]:
n_trials = nrows = 10 **5
n_dice = ncols = 8

In [138]:
toss = np.random.choice([0, 1], n_trials * n_dice).reshape(nrows, ncols)
toss

array([[1, 0, 1, ..., 0, 1, 0],
       [0, 0, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 0, 1],
       ...,
       [1, 0, 1, ..., 0, 1, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [0, 1, 1, ..., 1, 0, 1]])

In [129]:
#create a dataframe to get columns for rolls

coin_toss = (pd.DataFrame(toss))
coin_toss.shape

(100000, 8)

In [130]:
coin_toss.head()

0  1  2  3  4  5  6  7
0  0  0  0  1  0  0  1  0
1  1  1  1  0  0  0  1  0
2  0  0  0  0  1  0  1  0
3  1  0  1  0  1  1  1  1
4  0  1  0  0  1  1  1  1

In [131]:
coin_toss.columns

RangeIndex(start=0, stop=8, step=1)

In [132]:
coin_toss.columns = ['t1','t2','t3','t4','t5','t6','t7','t8']

In [133]:
coin_toss.columns

Index(['t1', 't2', 't3', 't4', 't5', 't6', 't7', 't8'], dtype='object')

In [134]:
coin_toss.sum(axis=1) 

0        2
1        4
2        2
3        6
4        5
        ..
99995    2
99996    5
99997    3
99998    7
99999    5
Length: 100000, dtype: int64

In [135]:
coin_toss.sum(axis=1) == 3

0        False
1        False
2        False
3        False
4        False
         ...  
99995    False
99996    False
99997     True
99998    False
99999    False
Length: 100000, dtype: bool

In [136]:
(coin_toss.sum(axis=1) == 3).mean()

0.21768

#### ANSWER: a 0.22 probability rate

In [140]:
### (toss.sum(axis=1) == 3).mean() note: IF I want an array, I could just run everything that is not part or or named the df and call as the array

### 3) There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [157]:
ds_student = .25 #1 out of 4 total students is a DS student, so .25 rate

nbillb = ncols = 2
ntrials = nrows = 10**5

In [158]:
data = np.random.random((nrows, ncols))
data

array([[0.86375999, 0.28490597],
       [0.07325639, 0.7632372 ],
       [0.45271906, 0.54229687],
       ...,
       [0.40357016, 0.05170649],
       [0.45221073, 0.98827513],
       [0.85694009, 0.66611331]])

In [159]:
ds_billboard = data <= ds_student
ds_billboard

array([[False, False],
       [ True, False],
       [False, False],
       ...,
       [False,  True],
       [False, False],
       [False, False]])

In [172]:
ds_billboard.sum(axis=1)==2 #because True becomes 1 and False is 0, so in this case a True | True would == 2

array([False, False, False, ..., False, False, False])

In [171]:
(ds_billboard.sum(axis=1)==2).mean()

0.06336

#### ANSWER: a probablity of 0.06

### 4) Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

In [24]:
avg_tarts=3

days = ncols = 5
ntrials = nrows = 10**5

In [25]:
###Question: can we round these numbers to a whole?
poptarts = np.random.normal(3, 1.5,(nrows, ncols))
poptarts

array([[1.81206924, 4.92911661, 0.64680433, 4.96424919, 4.10878061],
       [1.49627406, 5.68750838, 3.33157082, 1.12786178, 6.76389712],
       [1.17593549, 2.40859248, 4.44860049, 3.6790932 , 6.3232411 ],
       ...,
       [2.16965061, 2.54280374, 4.69472573, 4.12449194, 3.27620942],
       [3.14927339, 1.25432179, 4.1988665 , 2.55448806, 2.3730019 ],
       [1.72718769, 0.20550175, 5.5258083 , 3.70090915, 4.19968801]])

In [56]:
(poptarts.sum(axis=1) < 17).mean()



0.72382

#### ANSWER: 0.72 probability

### 5) Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.

Since you have means and standard deviations, you can use np.random.normal to generate observations.

If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [61]:
mavg_height = 178

chosen1 = ncols = 1
ntrials = nrows = 10**5

guy_heights = np.random.normal(1, 8,(nrows, ncols))
guy_heights

array([[ -0.5011673 ],
       [-13.73724213],
       [ 12.86757683],
       ...,
       [  0.37775522],
       [ -1.33598659],
       [ -0.65480382]])

In [62]:
wavg_height = 170

chosen1 = ncols = 1
ntrials = nrows = 10**5

girl_heights = np.random.normal(1, 6,(nrows, ncols))
girl_heights

array([[ 0.75339422],
       [ 5.54487193],
       [-2.49414235],
       ...,
       [ 1.41238484],
       [ 0.81821118],
       [-8.65894083]])