In [2]:
%matplotlib inline
import numpy as np
import pandas as pd

np.random.seed(29)

### 1) How likely is it that you roll doubles when rolling two dice?

In [199]:
n_trials = nrows = 10**5
n_dice = ncols = 2

In [200]:
rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[3, 1],
       [4, 5],
       [4, 4],
       ...,
       [4, 5],
       [5, 2],
       [1, 3]])

In [201]:
#create a dataframe to get columns for rolls

rolls = (pd.DataFrame(rolls))

In [202]:
rolls.head()

0  1
0  3  1
1  4  5
2  4  4
3  6  2
4  3  3

In [203]:
rolls.columns

RangeIndex(start=0, stop=2, step=1)

In [204]:
#name the columns (roll vs roll2)
rolls.columns = ['rolls1','rolls2']

In [206]:
rolls.head()

rolls1  rolls2
0       3       1
1       4       5
2       4       4
3       6       2
4       3       3

In [45]:
#find the average of doubles rolled
(rolls.rolls1 == rolls.rolls2).mean()

0.16857

note: this makes sense as the probablity of two dice rolls being doubles as a 6:36 chance (6 sided dice X 6) and 0.16 = 1/6

### 2) If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [207]:
n_trials = nrows = 10 **5
n_dice = ncols = 8

In [211]:
toss = np.random.choice([0, 1], n_trials * n_dice).reshape(nrows, ncols)
toss

array([[1, 1, 1, ..., 0, 1, 0],
       [0, 1, 1, ..., 0, 1, 1],
       [1, 0, 0, ..., 1, 1, 0],
       ...,
       [0, 0, 1, ..., 1, 1, 0],
       [0, 1, 1, ..., 1, 1, 1],
       [1, 0, 0, ..., 0, 1, 0]])

In [212]:
#create a dataframe to get columns for rolls

coin_toss = (pd.DataFrame(toss))
coin_toss.shape

(100000, 8)

In [210]:
coin_toss.head()

0  1  2  3  4  5  6  7
0  1  0  0  1  1  1  1  1
1  0  0  1  1  1  0  0  0
2  0  1  0  0  1  1  0  0
3  1  0  1  1  0  0  1  1
4  0  0  1  1  1  0  1  1

In [131]:
coin_toss.columns

RangeIndex(start=0, stop=8, step=1)

In [132]:
coin_toss.columns = ['t1','t2','t3','t4','t5','t6','t7','t8']

In [133]:
coin_toss.columns

Index(['t1', 't2', 't3', 't4', 't5', 't6', 't7', 't8'], dtype='object')

In [134]:
coin_toss.sum(axis=1) 

0        2
1        4
2        2
3        6
4        5
        ..
99995    2
99996    5
99997    3
99998    7
99999    5
Length: 100000, dtype: int64

In [135]:
coin_toss.sum(axis=1) == 3

0        False
1        False
2        False
3        False
4        False
         ...  
99995    False
99996    False
99997     True
99998    False
99999    False
Length: 100000, dtype: bool

In [136]:
(coin_toss.sum(axis=1) == 3).mean()

0.21768

#### ANSWER: a 0.22 probability rate

In [213]:
### (toss.sum(axis=1) == 3).mean() note: IF I want an array, I could just run everything that is not part or or named the df and call as the array

### 3) There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [157]:
ds_student = .25 #1 out of 4 total students is a DS student, so .25 rate

nbillb = ncols = 2
ntrials = nrows = 10**5

In [158]:
data = np.random.random((nrows, ncols))
data

array([[0.86375999, 0.28490597],
       [0.07325639, 0.7632372 ],
       [0.45271906, 0.54229687],
       ...,
       [0.40357016, 0.05170649],
       [0.45221073, 0.98827513],
       [0.85694009, 0.66611331]])

In [159]:
ds_billboard = data <= ds_student
ds_billboard

array([[False, False],
       [ True, False],
       [False, False],
       ...,
       [False,  True],
       [False, False],
       [False, False]])

In [172]:
ds_billboard.sum(axis=1)==2 #because True becomes 1 and False is 0, so in this case a True | True would == 2

array([False, False, False, ..., False, False, False])

In [171]:
(ds_billboard.sum(axis=1)==2).mean()

0.06336

#### ANSWER: a probablity of 0.06

### 4) Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

In [218]:
avg_tarts=3

days = ncols = 5
ntrials = nrows = 10**5

In [219]:

poptarts = np.random.normal(3, 1.5, size =(nrows, ncols)).round()
poptarts

array([[ 5.,  5.,  2.,  3.,  6.],
       [ 2.,  4.,  2.,  3.,  3.],
       [ 3.,  3., -0.,  1.,  1.],
       ...,
       [ 1.,  2.,  2.,  0.,  3.],
       [ 4.,  4.,  1.,  2.,  3.],
       [ 4.,  6.,  4.,  0.,  4.]])

In [221]:
(poptarts.sum(axis=1) < 17).mean()

##note: can apply an absolute to make the dataset be only positive numbers (as the direction of poptart inventory is forward)

0.66972

#### ANSWER: 0.67 probability

### 5) Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.

Since you have means and standard deviations, you can use np.random.normal to generate observations.

If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [10]:
mavg_height = 178

chosen1 = ncols = 1
ntrials = nrows = 10**5

guy_heights = np.random.normal(1, 8,(nrows, ncols))
guy_heights

array([[  4.96842008],
       [ -8.68028656],
       [  3.64477165],
       ...,
       [ 13.62940747],
       [-10.30278642],
       [  1.95776978]])

In [11]:
wavg_height = 170

chosen1 = ncols = 1
ntrials = nrows = 10**5

girl_heights = np.random.normal(1, 6,(nrows, ncols))
girl_heights

array([[-4.19130207],
       [ 5.05392131],
       [ 7.18348881],
       ...,
       [-6.605055  ],
       [-4.55516745],
       [-7.64129639]])

In [13]:
women=np.random.normal(wavg_height, 6,(nrows, ncols))
women

array([[160.00630414],
       [167.78011631],
       [161.54364248],
       ...,
       [175.78834349],
       [171.41684885],
       [172.26252746]])

In [15]:
men=np.random.normal(mavg_height, 8,(nrows, ncols))
men

array([[181.03367464],
       [169.93161754],
       [167.04667803],
       ...,
       [175.1392877 ],
       [170.13350393],
       [172.6108165 ]])

In [17]:
(women.sum(axis=1) > men.sum(axis=1)).mean()

0.21224

#### ANSWER: there is a probability of 0.21 for the woman selected to be taller than the man selected

___________________________________________________________________

### 6) When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 

- What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

- What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [94]:
corrupted_dl= 0.004

numstudents = ncols = 100 
attempts = nrows = 10**5

In [95]:
dl_anaconda=np.random.random ((nrows, ncols))

In [97]:
dl_anaconda

array([[0.38490473, 0.26828342, 0.25564361, ..., 0.03948761, 0.56931254,
        0.82181899],
       [0.89608512, 0.5052493 , 0.6384398 , ..., 0.33753791, 0.28022828,
        0.28083271],
       [0.72565802, 0.08806667, 0.05348701, ..., 0.37938129, 0.55443681,
        0.01775028],
       ...,
       [0.04570286, 0.35678653, 0.58316237, ..., 0.77705172, 0.6239982 ,
        0.64766144],
       [0.85140992, 0.50826151, 0.34966152, ..., 0.49626068, 0.33678575,
        0.45520271],
       [0.94441759, 0.06348864, 0.84289128, ..., 0.06690955, 0.53281804,
        0.54311091]])

In [98]:
students_tries = dl_anaconda >= corrupted_dl

In [99]:
students_tries

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [100]:
students_tries.sum(axis=1)

array([100, 100, 100, ...,  99, 100, 100])

In [101]:
(students_tries.sum(axis=1) == 100 ).mean()

0.66971

#### ANSWER: 
- for 50 students with no download errors there is a <b> 0.82 probability </b>
- for 100 students, <b> 0.67 probability </b>
- for 150 students where there IS an installation issue, <b> 0.33 probability</b>

_________________________________________________________________

### 7) There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days.

- How unlikely is this?

- How likely is it that a food truck will show up sometime this week?

In [193]:
chance_of_food=0.70

numdays = ncols = 7 
trials = nrows = 10**5

In [194]:
array_of_trucks=np.random.choice([0,1], nrows * ncols, p = [.3, .7]).reshape(nrows, ncols)
array_of_trucks

array([[1, 0, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 0, 1, 1],
       ...,
       [1, 0, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 1, 0, 1],
       [0, 1, 1, ..., 0, 1, 1]])

In [195]:
array_of_trucks.shape

(100000, 7)

In [196]:
(array_of_trucks.sum(axis=1) > 0).mean()

0.99981

#### ANSWER: 
- It is 0.02 probability unlikely that there is not a truck
- It is 0.99 probability likely that a truck will show this week. 

_______________________________________________________________________

### 8) If 23 people are in the same room, what are the odds that two of them share a birthday? 
- What if it's 20 people? 
- 40?

In [223]:
n_rows = 10_000
n_cols = 23 

birthdays = np.random.choice(range(365), size = (n_rows, n_cols))
birthdays = pd.DataFrame(birthdays)
birthdays['n_unique']=birthdays.nunique(axis=1)

In [224]:
(birthdays.n_unique != 23).mean()

0.5032

ANSWER:  0.50 probability of 2 people out of 23 to share the same birthday